# Generated by Django 5.1.3 on 2024-11-11 18:22

import uuid

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("file", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "name",
                    models.CharField(
                        default="", max_length=150, verbose_name="Название"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        null=True,
                        verbose_name="Описание задачи",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("COMPLETED", "Выполнена"), ("OPEN", "Открыта")],
                        default="OPEN",
                        max_length=9,
                        verbose_name="Статус задачи",
                    ),
                ),
                ("due_date", models.DateTimeField(verbose_name="Дедлайн задачи")),
                (
                    "assignees",
                    models.ManyToManyField(
                        blank=True,
                        related_name="tasks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Назначенные исполнители на задачу",
                    ),
                ),
                (
                    "attachments",
                    models.ManyToManyField(
                        blank=True,
                        related_name="attachments",
                        to="file.file",
                        verbose_name="Файлы",
                    ),
                ),
            ],
            options={
                "verbose_name": "Задача",
                "verbose_name_plural": "Задачи",
                "ordering": ("created_at",),
            },
        ),
    ]
