# Generated by Django 5.1.3 on 2024-11-12 13:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("superuser", "Суперпользователь"),
                    ("administrator", "Администратор"),
                    ("performer_task", "Исполнитель задач"),
                ],
                default="performer_task",
                max_length=14,
                verbose_name="Роль пользователя системы",
            ),
        ),
    ]
